### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by Buyaki01**
- Created a new branch called testing
- Initialized RSpec
- Created enumerable_methods_spec.rb in the spec folder where I tested all the methods in the enumerable_methods.rb

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
The project requires changes.

**Comment by pelzolga123** [comment]
## Hi Ritta!
### You did an amazing job :+1: All methods are tested and all test are passing!
Just a few more changes left before this Pull Request can be approved:
* [ ] Stickler is not checking this Pull Request right now. Make sure you turned stickler on for this repository.
* [ ] Please add a part on how to run tests on your project to the README file.

[OPTIONAL]
*  Use `require_relative` for files in your directory instead of `require`, it's a ruby convention.

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by lekegitrepo** [comment]
#### Hi @Buyaki01 :+1:
#### Well done for implementing the changes required by the previous reviewer. This project is approved.

### Reviewed by Temitayo Adeleke.

**Review by lekegitrepo — APPROVED** [review]
#### Status: Approved.

**Pull request merged**
